# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20181112_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='complete',
            new_name='visited',
        ),
    ]
