# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20181113_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='comment',
            field=models.CharField(default=django.utils.timezone.now, max_length=280),
            preserve_default=False,
        ),
    ]
