# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_restaurants_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='comment',
            field=models.CharField(default=None, max_length=280),
        ),
    ]
