# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 15:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20181115_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(blank=True, default=None, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='comment',
            field=models.TextField(blank=True, max_length=280),
        ),
    ]
