# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-15 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20181115_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
    ]
