# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20181119_2055'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
    ]
